on: [push,pull_request]
name: ops
jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        application: ['ojs','omp','ops']
        php-version: [ '8.1','8.2' ]
    steps:
      - uses: withanage/validate-action@v1
        with:
          application: '${{matrix.application}}'
          repository: '${{github.repository_owner}}'
          branch: '${{ github.head_ref || github.ref_name }}'
  test:
    name: test
    runs-on: ubuntu-latest
    # needs: validate
    strategy:
      fail-fast: false
      matrix:
        application: ['ojs','omp','ops']
        php-version: [ '8.1','8.2' ]
        database: [ 'pgsql', 'mysql','mariadb']
    steps:
      - uses: actions/checkout@v4

      - uses: withanage/test-action@v1
        with:
          application: '${{matrix.application}}'
          repository: '${{github.repository_owner}}'
          branch: '${{ github.head_ref || github.ref_name }}'
  upgrade:
    name: upgrade
    runs-on: ubuntu-latest
    # needs: test
    strategy:
      fail-fast: false
      matrix:
        application: ['ojs','omp','ops']
        dataset-branch: [ 'stable-3_4_0','stable-3_3_0','stable-3_2_1','stable-3_2_0' ]
        database: [ 'pgsql','mysql']
        php-version: [ '8.1' ]

    steps:
      - uses: withanage/upgrade-action@v1
        with:
          application: '${{matrix.application}}'
          repository: '${{github.repository_owner}}'
          branch: '${{ github.head_ref || github.ref_name }}'

