on: [push, pull_request]
name: pkp-lib
jobs:
  pkp-lib:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        application: ['omp','ojs','ops']
        database: ['pgsql','mysql']
        php-version: [ '7.3','7.4','8.0','8.1','8.2' ]

    name: pkp-lib
    steps:
      - uses: xmlFlow/pkp-github-actions@v1
        with:
          application:  ${{matrix.application}}
          repository: pkp
          branch: CURRENT_BRANCH
          node_version: 12
          upgrade_test: 'stable-3_2_0,stable-3_2_1,stable-3_3_0,stable-3_4_0'
  
  php8.2-bcmath php8.2-bz2 php8.2-curl php8.2-gd php8.2-intl php8.2-mbstring php8.2-mysql php8.2-mysqlnd php8.2-mysqli php8.2-opcache php8.2-pdo_mysql php8.2-pgsql php8.2-json php8.2-soap php8.2-xml php8.2-zip