on: [push, pull_request]
name: pkp-lib
jobs:
  pkp-lib:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        application: ['omp','ojs','ops']
        database: ['pgsql','mysql']
        php-version: [ '7.3','7.4','8.0','8.1','8.2' ]

    name: pkp-lib
    steps:
      - uses: xmlFlow/pkp-github-actions@v1
        with:
          application:  ${{matrix.application}}
          repository: pkp
          branch: stable-3_3_0
          node_version: 12
          upgrade_test: 'stable-3_2_0,stable-3_2_1,stable-3_3_0,stable-3_4_0'
  
